# To prevent cache invalidation from changes in fields other than dependencies
FROM endeveit/docker-jq AS deps
COPY package.json /tmp
RUN jq '{ dependencies, devDependencies }' < /tmp/package.json > /tmp/deps.json


FROM mcr.microsoft.com/playwright:v1.20.2-focal
WORKDIR /automation
COPY --from=deps /tmp/deps.json ./package.json

ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD 1
RUN npm ci

COPY . .

ENTRYPOINT ["/automation/entrypoint.sh"]