name: Run electron tests
on:
    push:
        branches: [main]

jobs:
    build:
        name: Build and run playwright in docker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}

            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'npm'
            - run: |
                  npm run dkr:build:pw
                  npm run dkr:run
